### PR TITLE
Update Swarm booster versions for RHOAR Alpha4 

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by ALRubinger** [comment]
@heiko-braun So @starksm64 has set this to SHA 99f6543450c7c1fb0ea31d9d252fbe6d694d8a73; is your tag of 1 here what's intended, or go with Scott's version?

**Comment by heiko-braun** [comment]
@ALRubinger No, it's needs to be 1. It contains additional fixes

**Comment by heiko-braun** [comment]
Let me rebase and resolve the conflict

**Comment by ALRubinger** [comment]
797a93da04d4f9604c250cfc80d2adcea0faf604

**Pull request closed without merging**
