### PR TITLE
[WIP] - Addition of node.js rest booster

### PR DESCRIPTION
**Pull request by lholmquist**
This PR adds a REST Level 0 booster for node.js.

This PR will be connected to other PRs in various repos, so this isn't to be merged yet.

Just getting the ball rolling with Node.js Integration

### CODE REVIEW

**Comment by gastaldi** [comment]
Excellent! Let us know when this PR is ready to be merged

**Comment by gastaldi** [comment]
This is needed for https://github.com/openshiftio/appdev-planning/issues/40

**Comment by lholmquist** [comment]
Now that the docs PR and the jenkins PR are merged in,  i suppose this could be ready?

**Comment by gastaldi** [comment]
Thanks!

**Pull request merged**
