### PR TITLE
Add version support to health-check

### PR DESCRIPTION
**Pull request by rdruss**

### CODE REVIEW

**Comment by gastaldi** [comment]
There are conflicts

**Comment by gastaldi** [comment]
Ah I forgot to mention that the yaml file name must be unique in the repository. The other merged PRs need to change too

**Comment by quintesse** [comment]
> Ah I forgot to mention that the yaml file name must be unique in the repository. The other merged PRs need to change too

The docs _explicitely_ mention it with bold font and exclamation marks ;)

**Comment by gastaldi** [comment]
Fixed in https://github.com/openshiftio/booster-catalog/commit/a04615a05e92f37010888eb75ad75e61b1d3b1db

**Pull request closed without merging**
