### PR TITLE
Define the 2 different versions of the Vert.x HTTP booster.

### PR DESCRIPTION
**Pull request by cescoffier**
Followed the guide to define 2 versions of the Vert.x HTTP booster.

@quintesse can you review it and let me know if I did something wrong?

For vert.x, we decided to use another repository to host the booster using the productized runtime:

1. the `community` version is there: https://github.com/openshiftio-vertx-boosters/vertx-http-booster
2. the `redhat` (product) version is there: https://github.com/openshiftio-vertx-boosters/vertx-http-booster-redhat

Both versions have the same `booster.yaml` file: https://github.com/openshiftio-vertx-boosters/vertx-http-booster-redhat/blob/master/.openshiftio/booster.yaml. This file defines the `community` and `redhat` version. The name of the `redhat` version is a temporary name until @jclingan or @rruss gives me the final name.

### CODE REVIEW

**Comment by quintesse** [comment]
THis PR looks good, the Booster repo itself still needs work though. It's `.openshiftio/booster-yaml` file still needs a `versions:` section. Something like:

```
name: Vert.x HTTP Booster
description: Runs a Vert.x HTTP application
versions:
- id: community
  name: Vert.x Community
```

for  https://github.com/openshiftio-vertx-boosters/vertx-http-booster

and something similar for  https://github.com/openshiftio-vertx-boosters/vertx-http-booster-redhat but with `id: redhat`.

**Comment by cescoffier** [comment]
@quintesse oups... forgot to push the community booster. Problem fixed.

**Comment by cescoffier** [comment]
@quintesse is it a PR we can merge, or do we have to wait?

**Comment by quintesse** [comment]
Great! Merged.

**Pull request merged**
